Assignment2
IntelliTect-Samples/EWU-CSCD371-2021-Winter pull request #28
Opened 2021-01-20 01:34 UTC by Sithale

Code compiled and tests run successfully.
No extra credit.

2021-01-24 19:18 UTC, NPThompson commented
I will review this.

2021-01-24 20:10 UTC, NPThompson requested changes
There is an existing BaseLogger class. It needs an auto property to hold the class name. This property should be set in the LogFactory using an object initializer. ✔
    Create a FileLogger that derives from BaseLogger. It should take in a path to a file to write the log message to. When its Log method is called, it should **append** messages on their own line in the file. The output should include all of the following: ❌
        The current date/time ✔
        The name of the class that created the logger ✔
        The log level ✔
        The message ✔
        The format may vary, but an example might look like this "10/7/2019 12:38:59 AM FileLoggerTests Warning: Test message"
    The LogFactory should be updated with a new method ConfigureFileLogger. This should take in a file path and store it in a private member. It should use this when instantiating a new FileLogger in its CreateLogger method. ✔
    If the file logger has not be configured in the LogFactory, its CreateLogger method should return null. ✔
    Inside of BaseLoggerMixins implement extension methods on BaseLogger for
        Error, ✔
        Warning, ✔
        Information, and ✔
        Debug. ✔ Each of these methods should take in a string for the message, as well as a parameter array of arguments for the message. Each of these extension methods is expected to be a shortcut for calling the BaseLogger.Log method, by automatically supplying the appropriate LogLevel. These methods should throw an exception if the BaseLogger parameter is null. There are a couple example unit tests to get you started.
    Use the nameof() operator when identifying the class name to the logger ✔
    Ensure you turn on Warnings as Errors (TreatWarningsAsErrors) ✔
    Ensure that you turn on code analysis (EnableNETAnalyzers) ✔
    Ensure that you turn on CodeAnalysisTreatWarningsAsErrors ✔
    Set LangVersion to 9.0 ✔
    Turn on Nullability (Nullable) ✔
    All of the above should be unit tested.

Everything looks good, except for these two things:
I had to modify the filepath in FileLoggerTests.cs. to get the test to pass. A relative filepath ("test.txt") works fine. The resulting file shows up (on my machine) in "\Logger.Tests\bin\debug\net5.0\". 
The ❌ is there because FileLogger does not append messages to files, it overwrites them. (I tried calling fileLog?.debug() multiple times inside of FileLogger_FilePathIsCreated, and the output file has only one line, the last logged message). Also, there is no test that assures that FileLogger appends messages to the log file.

2021-02-14 18:27 UTC, mmwoodfo reviewed
##  (Sithale)

## Assignment2

| Build/Compile (Build succeeded: 0 Error(s), 0 Warning(s))| **<10>** |
| --------------------- | ------ |
| Assignment compiles even though major pieces might be missing, or there are significant problems: **✔** |  **5** |


| Assignment  | **<10 (missing lots) - 20 (minor)>** |
| --------------------- | ------ |
| <Project Assignment Goes Here> | ❌✔ |


| Project Analysis |   |
| -----------------| - |
| Disabled Warnings **** | **✔**
| Nullable Enabled: | **❌** |
| Appropriately handle all warnings | **✔** |
| CodeReview Performed | ****-5**** |
| Add the code analysis packages and appropriately handle all warnings* |  **❌** |
*<sub><sup>`IntelliTectAnalyzer.dll`,`Microsoft.NetCore.Analyzers.dll`,`Microsoft.CodeQuality.Analyzers.dll`,`Microsoft.NetCore.Analyzers.dll`,`Microsoft.NetFramework.Analyzers.dll`. (It is okay to appropriately disable rules such as  localization/culture rules.)</sub></sup>


| ProjectName | Nullable | Solutions | Analyzers | Unexpected Disabled Warnings | Waning Level |
| -- | -- | -- | -- | -- | -- |
| Logger | Enable | Logger.sln |  |  | 4 |
| Logger.Tests | Enable | Logger.sln |  |  | 4 |
| LoginStuff | Disable |  |  |  | 4 |
| LoginStuff.Tests | Disable |  |  |  | 4 |


| Testing | **<0 - 20>** |
| --------------------- | ------ |
| Test Run FAILED: Total tests=11, Passed=10, Failed=1, Skipped=0 | **88%** |
| Unit test project fails to compile, most test fails, or contains significant problems. | **<10>** |
| Most assigned work is tested or contain some errors. | **<5>** |
| All assigned work is tested | **<5>** |


| Extra Credit | **<0 - 10>** |
| --------------------- | ------ |
| <Extra Credit Goes Here> | ❌✔ |

2021-02-14 18:27 UTC, mmwoodfo commented on Logger/LogFactory.cs
> +        private string FilePath { get; set; } = "";
```suggestion
        private string _FilePath;
```
Auto properties are typically only used for public members. You can use a private variable for your file path string.

2021-02-14 18:27 UTC, mmwoodfo commented on Logger/LogFactory.cs
> +                FilePath = this.FilePath
```suggestion
                FilePath = _FilePath
```
Avoid using `.this`. Also, you may consider passing your file path through the constructor rather than as an auto property.

2021-02-14 18:27 UTC, mmwoodfo commented on Logger/LogFactory.cs
> +            BaseLogger fileLog = new FileLogger()
```suggestion
            return new FileLogger()
```
Alternatively, you can return here rather than creating a new variable and returning the line below it.

2021-02-14 18:27 UTC, mmwoodfo commented on Logger/FileLogger.cs
> +        public string FilePath { get; set; } = "";
```suggestion
        private string _FilePath;
```
This should be private.

2021-02-14 18:27 UTC, mmwoodfo commented on Logger/FileLogger.cs
> +            using StreamWriter sw = File.CreateText(FilePath);
```suggestion
            using (StreamWriter sw = File.CreateText(FilePath))
            {
```

2021-02-14 18:27 UTC, mmwoodfo commented on Logger/FileLogger.cs
> +            sw.WriteLine($"{DateTime.Now} {this.ClassName} {logLevel} {message}");
```suggestion
            sw.WriteLine($"{DateTime.Now} {ClassName} {logLevel} {message}");
        }
```

2021-02-14 18:27 UTC, mmwoodfo commented on Logger/BaseLoggerMixins.cs
> +        public static void Error(this BaseLogger logNum, string message, params object[] paramArray)
```suggestion
        public static void Error(this BaseLogger? logger, string message, params object[] paramArray)
```
`logNum` is an odd name. Try to avoid using abbreviated variable names.

2021-02-14 18:27 UTC, mmwoodfo commented on Logger/BaseLogger.cs
> +        public string ClassName { get; set; } = "";
```suggestion
        public string? ClassName { get; set; };
```

2021-02-14 18:27 UTC, mmwoodfo commented on Logger.Tests/LogFactoryTests.cs
> +            LogFactory logFac = new LogFactory();
```suggestion
            LogFactory logFactory = new LogFactory();
```
Avoid using abbreviated names.

2021-02-14 18:27 UTC, mmwoodfo commented on Logger.Tests/LogFactoryTests.cs
> +            if(fileLog != null && !string.IsNullOrEmpty(fileLog.ClassName))
If this line is true, your test should fail on line 38. Avoid using conditional logic in unit tests if you can.

2021-02-14 18:27 UTC, mmwoodfo commented on Logger.Tests/LogFactoryTests.cs
> +            string filePath = "";
These should probably be in your `// Arrange` block.

2021-02-14 18:27 UTC, mmwoodfo commented on Logger.Tests/FileLoggerTests.cs
> +            logFac.ConfigureFileLogger("P:/.Net Programming Assignment 2/Logger/test.txt");
This test will fail - don't hard code file paths. If you want your test to pass, change it to be:
```suggestion
            logFac.ConfigureFileLogger("test.txt");
```
Or change it to use `Path.GetRandomFileName()` and store it in a variable.
Make sure to dispose of the file at the end of your unit test.
Your `StreamWriter` will automatically create a file for you.

2021-02-14 18:27 UTC, mmwoodfo commented on Logger.Tests/FileLoggerTests.cs
> +            // Assert
This unit test doesn't assert anything.

2021-02-14 18:27 UTC, mmwoodfo commented on Logger.Tests/FileLoggerTests.cs
> +            FileLogger? fileLog = (FileLogger?)logFac.CreateLogger(nameof(FileLoggerTests));
```suggestion
            FileLogger fileLog = new FileLogger("test.txt");
```
Generally speaking, when unit testing you only want to test one _unit_ of your code at a time. Since you are testing your `FileLogger` and not your `LogFactory` you should directly instantiate a new `FileLogger`.

2021-02-14 18:27 UTC, mmwoodfo commented on Logger.Tests/FileLoggerTests.cs
> +            fileLog?.Debug("Message {0}", 531);
```suggestion
            fileLog.log(LogLevel.Debug, "Message {0}");
```
We are only testing the `FileLogger` here. Not the extension methods for it. That should be taken care of in a separate unit test.

2021-02-14 18:27 UTC, mmwoodfo commented on Logger/BaseLoggerMixins.cs
> +        public static void Warning(this BaseLogger logNum, string message, params object[] paramArray)
```suggestion
        public static void Warning(this BaseLogger? logNum, string message, params object[] paramArray)
```
You should make your `BaseLogger` as nullable, as we are allowing null values to be passed through. This will prevent you from having to use the `!` operator in your unit tests.

2021-02-14 18:27 UTC, mmwoodfo commented on Logger.Tests/BaseLoggerMixinsTests.cs
> +            BaseLoggerMixins.Warning(null!, "");
```suggestion
            BaseLoggerMixins.Warning(null, "");
```
Mark your `BaseLogger` parameter as nullable.

2021-02-14 18:28 UTC, closed without merging